services:
  gateway:
    image: gateway_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      - order_service
      - product_service
      - user_service
      - report_service

  order_service:
    image: order_service
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - product_service
      - rabbitmq

  product_service:
    image: product_service
    environment:
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - rabbitmq

  user_service:
    image: user_service
    environment:
      - ASPNETCORE_URLS=http://+:5002

  report_service:
    image: report_service
    environment:
      - ASPNETCORE_URLS=http://+:5003
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
